# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20160209_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_date',
            new_name='date_of_group',
        ),
    ]
